### ISSUE TITLE
caching the result

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/chatgpt-plugin#14]
if you query github for an organization, you shold cache the result, storing it in the redis.
when you do a reques for an organization, first check in the cache, then execute the request to github so you can give quick anwers for known organizations.

**Comment by molinari135** [comment]
when connecting to redis it says this:
`redis.exceptions.NoPermissionError: this user has no permissions to access one of the keys used as arguments`

**Comment by ghost** [comment]
@burraco135 normally keys used in redis should start with a prefix which depends on the namespace being used to deploy the relevant openwhisk actions. For instance if the plugin actions are deployed under the namespace nuvolaris redis key should start with the prefix `nuvolaris:`. 

Not sure about the user being used to deploy chatgpt plugin, if it is gptuser for instance, then redis key should have the prefix `gptuser:`

To be clear this rule about redis key prefix it is valid for nuvolaris environment as all deployed users shares the same redis instance, and redis access right are managed using a prefix.
